# Generated by Django 6.0.7 on 2026-07-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Projeto em Destaque', help_text='Rótulo acima do título (ex: "Projeto em Destaque")', max_length=100, verbose_name='Label')),
                ('titulo', models.CharField(help_text='Nome do projeto', max_length=200, verbose_name='Título do Projeto')),
                ('descricao', models.TextField(help_text='Descrição do projeto (3-5 linhas)', verbose_name='Descrição')),
                ('imagem_principal', models.ImageField(help_text='Screenshot principal do projeto. Tamanho recomendado: 1200x800px', upload_to='projects/', verbose_name='Imagem Principal')),
                ('link_projeto', models.URLField(blank=True, help_text='URL do projeto ao vivo (opcional)', verbose_name='Link do Projeto')),
                ('link_repositorio', models.URLField(blank=True, help_text='URL do repositório no GitHub (opcional)', verbose_name='Link do Repositório')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar do site sem deletar', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem adicional do projeto. Tamanho recomendado: 1200x800px', upload_to='projects/gallery/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Legenda opcional para a imagem', max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem no carrossel (menor primeiro)', verbose_name='Ordem')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens do Projeto',
                'ordering': ['order'],
            },
        ),
    ]
