# Generated by Django 6.0.7 on 2026-07-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(help_text='Nome exibido no logo da página (ex: "Meu Portfólio")', max_length=100, verbose_name='Nome do Site')),
                ('titulo', models.CharField(help_text='Título que aparece na aba do navegador (SEO)', max_length=200, verbose_name='Título da Página')),
                ('headline', models.CharField(help_text='Frase de impacto no hero (ex: "Judges a book by its cover")', max_length=300, verbose_name='Headline Principal')),
                ('subtitulo', models.CharField(help_text='Texto acima da headline (ex: "Um Desenvolvedor que...")', max_length=300, verbose_name='Subtítulo')),
                ('cargo_atual', models.CharField(help_text='Seu cargo atual (ex: "Engenheiro de Software")', max_length=150, verbose_name='Cargo Atual')),
                ('empresa_atual', models.CharField(help_text='Nome da empresa onde trabalha atualmente', max_length=150, verbose_name='Empresa Atual')),
                ('link_empresa', models.URLField(blank=True, help_text='URL do site da empresa', verbose_name='Link da Empresa')),
                ('sobre_mim', models.TextField(help_text='Texto descritivo exibido na seção hero (2-3 frases)', verbose_name='Sobre Mim')),
                ('foto_perfil', models.ImageField(help_text='Foto/avatar exibido no hero. Tamanho recomendado: 500x500px', upload_to='profile/', verbose_name='Foto de Perfil')),
                ('texto_disponibilidade', models.TextField(help_text='Texto exibido na seção de tecnologias (ex: "Atualmente buscando ingressar em um time multidisciplinar...")', verbose_name='Texto de Disponibilidade')),
                ('email_contato', models.EmailField(help_text='E-mail exibido na seção de contato', max_length=254, verbose_name='E-mail de Contato')),
                ('link_github', models.URLField(blank=True, help_text='URL do perfil no GitHub', verbose_name='GitHub')),
                ('link_linkedin', models.URLField(blank=True, help_text='URL do perfil no LinkedIn', verbose_name='LinkedIn')),
                ('link_instagram', models.URLField(blank=True, help_text='URL do perfil no Instagram', verbose_name='Instagram')),
                ('link_twitter', models.URLField(blank=True, help_text='URL do perfil no Twitter/X', verbose_name='Twitter / X')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição do site para mecanismos de busca (150-160 caracteres recomendados)', verbose_name='Meta Description (SEO)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
