# Generated by Django 6.0.7 on 2026-07-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do projeto ou posição (ex: "App Mobile para E-commerce")', max_length=200, verbose_name='Título')),
                ('empresa', models.CharField(help_text='Nome da empresa ou cliente', max_length=200, verbose_name='Empresa')),
                ('descricao', models.TextField(help_text='Descrição curta do trabalho realizado (2-3 linhas)', verbose_name='Descrição')),
                ('icone', models.ImageField(blank=True, help_text='Imagem ou ícone do card. Tamanho recomendado: 400x300px', upload_to='experiences/', verbose_name='Ícone / Imagem')),
                ('link', models.URLField(blank=True, help_text='URL para mais detalhes (opcional)', verbose_name='Link "Saiba Mais"')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar do site sem deletar', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['order'],
            },
        ),
    ]
