# Generated by Django 6.0.7 on 2026-07-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: "Python", "React", "Docker"', max_length=100, verbose_name='Nome da Tecnologia')),
                ('icone', models.ImageField(help_text='Ícone da tecnologia (PNG com fundo transparente). Tamanho recomendado: 80x80px', upload_to='skills/', verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro na órbita', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['order'],
            },
        ),
    ]
